export default {
    nextButton: 'Siguiente',
    prevButton: 'Anterior',
    finishButton: 'Finalizar',
    cancelButton: 'Cancelar',
    confirmButton: 'Confirmar',
    closeButton: 'Cerrar',
    submitButton: 'Enviar',
    searchButton: 'Buscar',
    selectButton: 'Seleccionar',
    addButton: 'Agregar',
    removeButton: 'Eliminar',
    editButton: 'Editar',
    seleccionarHorario: 'Selecciona un horario',
}