export default {
    naranjaColor: '#ff5900',
    naranjaSecundarioColor: '#ffba8b',
    arenaColor: '#997747',
    negroColor: '#231f20',
    blancoColor: '#ffffff',
    transparent: 'transparent',
    black: '#231f20',
    darkGray: '#4b515f',
    white: '#ffffff',
    extraLightOrange: '#fbdada',
    lightOrange: '#ffbf9b',
    orange: '#ff5900',
    redColor: '#ff0000',
}