export default {
    nextButton: 'Siguiente',
    prevButton: 'Anterior',
    finishButton: 'Finalizar',
    cancelButton: 'Cancelar',
    confirmButton: 'Confirmar',
    closeButton: 'Cerrar',
    submitButton: 'Enviar',
    searchButton: 'Buscar',
    selectButton: 'Seleccionar',
    addButton: 'Agregar',
    removeButton: 'Eliminar',
    editButton: 'Editar',
    seleccionarHorario: 'Selecciona un horario',
    seleccionarMateria: 'Selecciona una materia',
    seleccionarFecha: 'Selecciona una fecha',
    seleccionarAsesor: 'Selecciona un asesor',
    solicitarAsesoria: 'Solicitar asesoría',
    error: 'Ha ocurrido un error',
}